title: "Fluente-Mente"
description: "Impara inglese in modo semplice, pratico e sostenibile."
url: "https://nausica-c.github.io"
baseurl: "/Fluente-Mente"

language: "it"
timezone: "Europe/Rome"

markdown: kramdown
permalink: /:categories/:title/

theme: null

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  inglese:
    output: true

defaults:

  # POSTS
  - scope:
      path: ""
      type: "posts"

    values:
      layout: "post"
      author: "Fluente-Mente"
      language: "inglese"

  # CLUSTER PAGES
  - scope:
      path: "inglese"

    values:
      layout: "cluster"

sass:
  style: compressed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

include:
  - _pages

seo:
  type: "website"
  name: "Fluente-Mente"

social:
  name: "Fluente-Mente"

navigation:
  - title: "Metodo"
    url: "/inglese/metodo/"

  - title: "Speaking"
    url: "/inglese/speaking/"

  - title: "Beginner"
    url: "/inglese/beginner/"

  - title: "Business"
    url: "/inglese/business/"

  - title: "Mindset"
    url: "/inglese/mindset/"
